spring:
  application:
    name: Ticket Campaigns
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketcampaigns
    username: user
    password: password
