INSERT INTO quarter_campaign (start_date, end_date) VALUES ('2020-03-29', '2020-06-28');
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 0, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  1, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  2, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  3, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  4, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  5, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  6, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  7, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  8, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  9, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  10, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  11, 3);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(),  12, 3);

INSERT INTO quarter_campaign (start_date, end_date) VALUES ('2020-09-28', '2020-12-27');
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 0, 10);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 1, 10);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 2, 10);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 3, 10);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 4, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 5, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 6, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 7, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 8, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 9, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 10, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 11, 9);
INSERT INTO quarter_campaign_weekly_tickets (quarter_campaign_id, week_index, weekly_tickets) VALUES (LASTVAL(), 12, 9);